default_platform(:ios)

platform :ios do
  desc "Build and upload the App to TestFlight."
  lane :beta do


    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_KEY_ISSUER"],
      key_filepath: ENV["API_KEY_LOCATION"]
    )

    pilot(
      api_key: api_key,
      ipa: ENV["APP_IPA_PATH"],
      beta_app_review_info: {
        contact_email: "contact@philippmatth.es",
        contact_first_name: "Philipp",
        contact_last_name: "Matthes",
        contact_phone: "017642090978",
        notes: "Thank you for reviewing the OUTPUT.DD App!"
      },
      localized_app_info: {
        "default": {
          feedback_email: "feedback@philippmatth.es",
          marketing_url: "https://output-dd.de",
          privacy_policy_url: "https://output-dd.de/datenschutz-output-app",
          description: "This is the TestFlight Beta version for the OUTPUT.DD App.",
        },
      },
      localized_build_info: {
        "default": {
          whats_new: "Default changelog",
        },
      }
    )
  end
end
